require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/cash_balances", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # CashBalance. As you add validations to CashBalance, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CashBalance.create! valid_attributes
      get cash_balances_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      cash_balance = CashBalance.create! valid_attributes
      get cash_balance_url(cash_balance)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_cash_balance_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      cash_balance = CashBalance.create! valid_attributes
      get edit_cash_balance_url(cash_balance)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CashBalance" do
        expect {
          post cash_balances_url, params: { cash_balance: valid_attributes }
        }.to change(CashBalance, :count).by(1)
      end

      it "redirects to the created cash_balance" do
        post cash_balances_url, params: { cash_balance: valid_attributes }
        expect(response).to redirect_to(cash_balance_url(CashBalance.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CashBalance" do
        expect {
          post cash_balances_url, params: { cash_balance: invalid_attributes }
        }.to change(CashBalance, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post cash_balances_url, params: { cash_balance: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested cash_balance" do
        cash_balance = CashBalance.create! valid_attributes
        patch cash_balance_url(cash_balance), params: { cash_balance: new_attributes }
        cash_balance.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the cash_balance" do
        cash_balance = CashBalance.create! valid_attributes
        patch cash_balance_url(cash_balance), params: { cash_balance: new_attributes }
        cash_balance.reload
        expect(response).to redirect_to(cash_balance_url(cash_balance))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        cash_balance = CashBalance.create! valid_attributes
        patch cash_balance_url(cash_balance), params: { cash_balance: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested cash_balance" do
      cash_balance = CashBalance.create! valid_attributes
      expect {
        delete cash_balance_url(cash_balance)
      }.to change(CashBalance, :count).by(-1)
    end

    it "redirects to the cash_balances list" do
      cash_balance = CashBalance.create! valid_attributes
      delete cash_balance_url(cash_balance)
      expect(response).to redirect_to(cash_balances_url)
    end
  end
end
